##Task 1: Unit Conversion


In [ ]:
def unit_conversion():
  """
  This function converts units between different units.
  """
  print("Choose Unit Conversion Type!")
  print("1. Length (meters <-> feet)")
  print("2. Weight (kilograms <-> pounds)")
  print("3. Volume (liters <-> gallons)")

  try:
    userin = int(input("Enter your choice (1, 2 0r 3): "))

    if userin == 1:
      val = float(input("Enter value: "))
      unit = input("Enter unit (m/ft): ").lower()

      if unit == "m":
        print(f"{val} meters = {val * 3.28084} feet")
      elif unit == "ft":
        print(f"{val} feet = {val / 3.28084} meters")
      else:
        print("Invalid unit!")


    elif userin == 2:
      val = float(input("Enter value: "))
      unit = input("Enter unit (kg/lb): ").lower()

      if unit == "kg":
        print(f"{val} kilograms = {val * 2.20462} pounds")
      elif unit == "lb":
        print(f"{val} pounds = {val / 2.20462} kilograms")
      else:
        print("Invalid unit!")


    elif userin == 3:
      val = float(input("Enter value: "))
      unit = input("Enter unit (l/gal): ").lower()

      if unit == "l":
        print(f"{val} liters = {val * 0.264172} gallons")
      elif unit == "gal":
        print(f"{val} gallons = {val / 0.264172} liters")
      else:
        print("Invalid unit!")


    else:
      print("Invalid choice!")

  except ValueError:
      print("Invalid input. Please enter a number.")

unit_conversion()

Choose Unit Conversion Type!
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter your choice (1, 2 0r 3): 2
Enter value: 60
Enter unit (kg/lb): kg
60.0 kilograms = 132.2772 pounds


##Task 2: Mathematical Operations

In [ ]:
def operations():
  """
  This function performs mathematical operations on a list of numbers.
  """

  try:
    operatenum = list(map(float, input("Enter numbers separated by spaces: ").split()))
    if not operatenum:
      raise ValueError("List is empty!!")

    print("Choose Mathematical Operation: ")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    userin = int(input("Enter your choice (1, 2, 3 or 4): "))

    if userin == 1:
      print(f"Sum: {sum(operatenum)}")
    elif userin == 2:
      print(f"Average: {sum(operatenum) / len(operatenum)}")
    elif userin == 3:
      print(f"Maximum: {max(operatenum)}")
    elif userin == 4:
      print(f"Minimum: {min(operatenum)}")
    else:
      print("Invalid choice!")

  except ValueError as e:
    print(f"Error: {e}")

operations()


Enter numbers separated by spaces: 4 2 8 15
Choose Mathematical Operation: 
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1, 2, 3 or 4): 1
Sum: 29.0


##Task 3: List Manipulation

In [ ]:
def extract_every_other(lst):
  return lst[::2]

def get_sublist(lst, start, end):
  return lst[start:end+1]

def reverse_list(lst):
  return lst[::-1]

def remove_first_last(lst):
  return lst[1:-1]

def get_first_n(lst, n):
  return lst[:n]

def get_last_n(lst, n):
  return lst[-n:]

def reverse_skip(lst):
  return lst[::-2]

if __name__ == "__main__":
  user_lst = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
  print("Original List:", user_lst)

  print("Extracted every other element:", extract_every_other(user_lst))
  start, end = map(int, input("Enter start and end indices (space-separated): ").split())
  print(f"Sublist from index {start} to {end}:", get_sublist(user_lst, start, end))

  print("Reversed List:", reverse_list(user_lst))

  print("List after removing first and last elements:", remove_first_last(user_lst))

  n = int(input("Enter the value of n: "))
  print(f"First {n} elements:", get_first_n(user_lst, n))

  print(f"Last {n} elements:", get_last_n(user_lst, n))

  print("Reversed List with Skipped Elements:", reverse_skip(user_lst))

Enter a list of numbers separated by spaces: 4 2 8 15 6 23
Original List: [4, 2, 8, 15, 6, 23]
Extracted every other element: [4, 8, 6]
Enter start and end indices (space-separated): 0 3
Sublist from index 0 to 3: [4, 2, 8, 15]
Reversed List: [23, 6, 15, 8, 2, 4]
List after removing first and last elements: [2, 8, 15, 6]
Enter the value of n: 2
First 2 elements: [4, 2]
Last 2 elements: [6, 23]
Reversed List with Skipped Elements: [23, 15, 2]


##Task 4: Nested List

In [ ]:
def flatten(lst):
  flat_list = []
  for item in lst:
    if isinstance(item, list):
      flat_list.extend(flatten(item))
    else:
      flat_list.append(item)
  return flat_list

def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

def sum_nested(lst):
    return sum(flatten(lst))

def remove_element(lst, elem):
    return [[x for x in sublist if x != elem] for sublist in lst]

def find_max(lst):
    return builtins.max(flatten(lst))

def count_occurrences(lst, elem):
    return flatten(lst).count(elem)

def deep_flatten(lst):
    return flatten(lst)

def average_nested(lst):
    flat = flatten(lst)
    return sum(flat) / len(flat)
import builtins


nested_lst = [[1, 2], [3, [4, 5]], 6]
print("Flattened list:", flatten(nested_lst))
print("Accessing [1, 2]:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print("Sum of elements:", sum_nested(nested_lst))
print("Remove 2:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("Max element:", find_max(nested_lst))
print("Count 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("Deep Flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("Average:", average_nested([[1, 2], [3, 4], [5, 6]]))

Flattened list: [1, 2, 3, 4, 5, 6]
Accessing [1, 2]: 6
Sum of elements: 21
Remove 2: [[1], [3], [4, 5]]
Max element: 6
Count 2: 3
Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average: 3.5


##Problem 1: Array Creation

In [ ]:
import numpy as np

emptyarr = np.empty((2,2))
print("Empty Array: \n",emptyarr)

onearr = np.ones((4,2))
print("One Array: \n",onearr)

filledarr = np.full((3,3),15)
print("Filled Array: \n",filledarr)

referencearr = np.array([[1,2,3],[4,5,6]])
zeros_like_arr = np.zeros_like(referencearr)
print("Zeros Like Array: \n",zeros_like_arr)

ones_like_arr = np.ones_like(referencearr)
print("Ones Like Array: \n",ones_like_arr)

new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("Numpy Array: \n",numpy_array)

Empty Array: 
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
One Array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled Array: 
 [[15 15 15]
 [15 15 15]
 [15 15 15]]
Zeros Like Array: 
 [[0 0 0]
 [0 0 0]]
Ones Like Array: 
 [[1 1 1]
 [1 1 1]]
Numpy Array: 
 [1 2 3 4]


##Problem 2: Array Manipulation

In [ ]:
import numpy as np

arr_10_to_49 = np.arange(10,50)
print("Array with values from 10 to 49: \n",arr_10_to_49)
mat_3 = np.arange(9).reshape(3,3)
print("3*3 Matrix: ",mat_3)

identity_matrix = np.eye(3)
print("3*3 Identity Matrix: \n",identity_matrix)

randomarr = np.random.random(30)
mean = randomarr.mean()
print("Random array of size 30: \n", randomarr)
print("Mean of Random Array: ",mean)

random_10 = np.random.random((10,10))
min_val = random_10.min()
max_val = random_10.max()
print("Minimum Value: ",min_val)
print("Maximum Value: ",max_val)

zeroarr = np.zeros(10)
zeroarr[4] = 1
print("Array with value 1 at index 4: ",zeroarr)

arr = np.array([1,2,0,0,4,0])
reversedarr = arr[::-1]
print("Reversed Array: ",reversedarr)

borderarr = np.ones((5,5))
borderarr[1:-1, 1:-1] = 0
print("Bordered Array: \\n",borderarr)

checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern: \\n",checkerboard)

Array with values from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3*3 Matrix:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
3*3 Identity Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array of size 30: 
 [0.94052385 0.6839488  0.49673443 0.81590817 0.05415001 0.8134597
 0.39971137 0.691331   0.09517584 0.73013872 0.96082425 0.76445051
 0.29199596 0.3996023  0.50063738 0.95796202 0.24127178 0.75984626
 0.97452427 0.71978124 0.88865663 0.75510177 0.78461823 0.56577081
 0.83196342 0.68568791 0.70275456 0.25125678 0.15532234 0.84550824]
Mean of Random Array:  0.6252872849101323
Minimum Value:  0.00287319127079122
Maximum Value:  0.9925289760733117
Array with value 1 at index 4:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array:  [0 4 0 0 2 1]
Bordered Array: \n [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checkerboard Pattern: \n [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1

##Problem 3: Array Operations

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

matadd = x+y
print("Addition of x and y: \n",matadd)

matsub = x-y
print("Subtraction of x and y: \n",matsub)

matmulx = x*2
print("Multiplication of x by 2: \n",matmulx)

matsqx = np.square(x)
print("Square of x: \n",matsqx)

dotvw = np.dot(v,w)
dotxv = np.dot(x,v)
dotxy = np.dot(x,y)

print("Dot Product of v and w: ",dotvw)
print("Dot Product of x and v: ",dotxv)
print("Dot Product of x and y: \n",dotxy)

concatxy_row = np.concatenate((x,y), axis = 0)
concatvw_col = np.vstack((v,w))

print("Concatenation of x and y row-wise: \n",concatxy_row)
print("Concatenation of v and w column-wise: \n",concatvw_col)

try:
  concatxv = np.concatenate((x,v), axis = 0)
  print("Concatenation of x and v row-wise: \n",concatxv)
except ValueError as e:
  print("Error: ",e)
  print("Concatenation of x and v row-wise is not possible as shapes of x (2*2) and v (1*2) do not match along the concenation axis.")

Addition of x and y: 
 [[ 6  8]
 [10 13]]
Subtraction of x and y: 
 [[-4 -4]
 [-4 -3]]
Multiplication of x by 2: 
 [[ 2  4]
 [ 6 10]]
Square of x: 
 [[ 1  4]
 [ 9 25]]
Dot Product of v and w:  219
Dot Product of x and v:  [29 77]
Dot Product of x and y: 
 [[19 22]
 [50 58]]
Concatenation of x and y row-wise: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w column-wise: 
 [[ 9 10]
 [11 12]]
Error:  all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Concatenation of x and v row-wise is not possible as shapes of x (2*2) and v (1*2) do not match along the concenation axis.


##Problem - 4: Matrix Operations

In [ ]:
import numpy as np


A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^(-1) = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^(-1):\n", identity_matrix)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB == BA:", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", B_T_A_T)
print("(AB)^T == B^T * A^T:", np.array_equal(AB_T, B_T_A_T))

# Solve system of linear equations using inverse method
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X (AX = B) using inverse method
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("Solution for the system of equations (x, y, z):", X)


A * A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA: False
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T: True
Solution for the system of equations (x, y, z): [ 2.  1. -2.]


##How fast is Numpy?

In [ ]:
import numpy as np
import time

# 1. Element-wise Addition
size = 1_000_000

# Using Python lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Python List Addition Time: {end_time - start_time:.5f} seconds")

# Using NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
arr_addition = arr1 + arr2
end_time = time.time()
print(f"NumPy Array Addition Time: {end_time - start_time:.5f} seconds")

# 2. Element-wise Multiplication
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Python List Multiplication Time: {end_time - start_time:.5f} seconds")

start_time = time.time()
arr_multiplication = arr1 * arr2
end_time = time.time()
print(f"NumPy Array Multiplication Time: {end_time - start_time:.5f} seconds")

# 3. Dot Product
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Python List Dot Product Time: {end_time - start_time:.5f} seconds")

start_time = time.time()
dot_product_numpy = np.dot(arr1, arr2)
end_time = time.time()
print(f"NumPy Dot Product Time: {end_time - start_time:.5f} seconds")

# 4. Matrix Multiplication
matrix_size = 1000

# Using Python lists
matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]

start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size))
                  for j in range(matrix_size)] for i in range(matrix_size)]
end_time = time.time()
print(f"Python List Matrix Multiplication Time: {end_time - start_time:.5f} seconds")

# Using NumPy arrays
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"NumPy Matrix Multiplication Time: {end_time - start_time:.5f} seconds")


Python List Addition Time: 0.09094 seconds
NumPy Array Addition Time: 0.00480 seconds
Python List Multiplication Time: 0.07875 seconds
NumPy Array Multiplication Time: 0.00427 seconds
Python List Dot Product Time: 0.10529 seconds
NumPy Dot Product Time: 0.00223 seconds
Python List Matrix Multiplication Time: 184.65227 seconds
NumPy Matrix Multiplication Time: 1.78362 seconds
